### ISSUE TITLE
Uninstall drops entire conversations table 

### ISSUE THREAD

**Issue by jgknight** [tvb/ConversationWarning#3]
There is a problem in the uninstall() function of this plugin. On line 109 it's using ->drop("warning") when it needs to be using ->dropColumn("warning").  This results in the forums entire conversations table being dropped!

http://esotalk.org/forum/1769-what-does-that-mean-and-how-to-solve-this-error/

**Comment by tvb** [comment]
Uh oh.. damn. Thanks for the PR.
